[project]
name = "satans_lil_helper"
version = "0.5.0"

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true

[tool.pytest.ini_options]
addopts = [
	"--import-mode=importlib",
	"-ra",
	"--durations=3",
	"--strict-markers",
	"--cov-report=html",
	"--cov-branch",
]
pythonpath = "src"
markers = [
	"slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
xfail_strict = true

[tool.coverage.report]
exclude_also = [
	"raise NotImplementedError",
	"if TYPE_CHECKING:",
	"@(abc\\.)?abstractmethod",
]

[tool.mypy]
check_untyped_defs = true
python_version = "3.12"

[tool.ruff.lint]
extend-select = [
			"FA",
			"ICN",
			"RET",
			"SIM",
			"TC",
			"PTH",
			"ERA",
			"PLW",
			"I",
			"N",
			"UP",
			"ANN",
			"FBT",
			"B",
			"A",
			"C4",
			"ISC",
			"T20",
			"SLF",
			"PT",
			"PLC",
			"PLE",
			"PLW",
		]