//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatansLilHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilePaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilePaths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatansLilHelper.FilePaths", typeof(FilePaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Tiles/Forest/Floor/000.
        /// </summary>
        internal static string ForestFloor {
            get {
                return ResourceManager.GetString("ForestFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Tiles/Forest/Wall/000.
        /// </summary>
        internal static string ForestWall {
            get {
                return ResourceManager.GetString("ForestWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music/hide_and_seek.
        /// </summary>
        internal static string HideAndSeek {
            get {
                return ResourceManager.GetString("HideAndSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_1_outline.
        /// </summary>
        internal static string Keyboard1 {
            get {
                return ResourceManager.GetString("Keyboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_2_outline.
        /// </summary>
        internal static string Keyboard2 {
            get {
                return ResourceManager.GetString("Keyboard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_3_outline.
        /// </summary>
        internal static string Keyboard3 {
            get {
                return ResourceManager.GetString("Keyboard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_4_outline.
        /// </summary>
        internal static string Keyboard4 {
            get {
                return ResourceManager.GetString("Keyboard4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_6_outline.
        /// </summary>
        internal static string Keyboard6 {
            get {
                return ResourceManager.GetString("Keyboard6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_7_outline.
        /// </summary>
        internal static string Keyboard7 {
            get {
                return ResourceManager.GetString("Keyboard7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_8_outline.
        /// </summary>
        internal static string Keyboard8 {
            get {
                return ResourceManager.GetString("Keyboard8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_9_outline.
        /// </summary>
        internal static string Keyboard9 {
            get {
                return ResourceManager.GetString("Keyboard9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_delete_outline.
        /// </summary>
        internal static string KeyboardDelete {
            get {
                return ResourceManager.GetString("KeyboardDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_arrow_down_outline.
        /// </summary>
        internal static string KeyboardDown {
            get {
                return ResourceManager.GetString("KeyboardDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_escape_outline.
        /// </summary>
        internal static string KeyboardEscape {
            get {
                return ResourceManager.GetString("KeyboardEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_f_outline.
        /// </summary>
        internal static string KeyboardF {
            get {
                return ResourceManager.GetString("KeyboardF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_h_outline.
        /// </summary>
        internal static string KeyboardH {
            get {
                return ResourceManager.GetString("KeyboardH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_i_outline.
        /// </summary>
        internal static string KeyboardI {
            get {
                return ResourceManager.GetString("KeyboardI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_insert_outline.
        /// </summary>
        internal static string KeyboardInsert {
            get {
                return ResourceManager.GetString("KeyboardInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_arrow_left_outline.
        /// </summary>
        internal static string KeyboardLeft {
            get {
                return ResourceManager.GetString("KeyboardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_page_down_outline.
        /// </summary>
        internal static string KeyboardPageDown {
            get {
                return ResourceManager.GetString("KeyboardPageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_page_up_outline.
        /// </summary>
        internal static string KeyboardPageUp {
            get {
                return ResourceManager.GetString("KeyboardPageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_return_outline.
        /// </summary>
        internal static string KeyboardReturn {
            get {
                return ResourceManager.GetString("KeyboardReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_arrow_right_outline.
        /// </summary>
        internal static string KeyboardRight {
            get {
                return ResourceManager.GetString("KeyboardRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_arrow_right_outline.
        /// </summary>
        internal static string KeyboardRightOutline {
            get {
                return ResourceManager.GetString("KeyboardRightOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_s_outline.
        /// </summary>
        internal static string KeyboardS {
            get {
                return ResourceManager.GetString("KeyboardS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_t_outline.
        /// </summary>
        internal static string KeyboardT {
            get {
                return ResourceManager.GetString("KeyboardT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/UI/Icons/keyboard_arrow_up_outline.
        /// </summary>
        internal static string KeyboardUp {
            get {
                return ResourceManager.GetString("KeyboardUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts/MenuFont.
        /// </summary>
        internal static string MenuFont {
            get {
                return ResourceManager.GetString("MenuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Enemies/Orc.
        /// </summary>
        internal static string Orc {
            get {
                return ResourceManager.GetString("Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Player/player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Satan/eyes_closed.
        /// </summary>
        internal static string SatanEyesClosed {
            get {
                return ResourceManager.GetString("SatanEyesClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Satan/eyes_open.
        /// </summary>
        internal static string SatanEyesOpen {
            get {
                return ResourceManager.GetString("SatanEyesOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Satan/main.
        /// </summary>
        internal static string SatanMain {
            get {
                return ResourceManager.GetString("SatanMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Satan/mouth_closed.
        /// </summary>
        internal static string SatanMouthClosed {
            get {
                return ResourceManager.GetString("SatanMouthClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Satan/mouth_open.
        /// </summary>
        internal static string SatanMouthOpen {
            get {
                return ResourceManager.GetString("SatanMouthOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music/night_time_scavenge1.
        /// </summary>
        internal static string Scavenge1 {
            get {
                return ResourceManager.GetString("Scavenge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music/night_time_scavenge2.
        /// </summary>
        internal static string Scavenge2 {
            get {
                return ResourceManager.GetString("Scavenge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts/StatusFont.
        /// </summary>
        internal static string StatusFont {
            get {
                return ResourceManager.GetString("StatusFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts/TitleFont.
        /// </summary>
        internal static string TitleFont {
            get {
                return ResourceManager.GetString("TitleFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Enemies/Wolf32.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
    }
}
