//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatansLilHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatansLilHelper.Properties.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End your turn?.
        /// </summary>
        internal static string ConfirmTurnEnd {
            get {
                return ResourceManager.GetString("ConfirmTurnEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal to Full.
        /// </summary>
        internal static string DebugHeal {
            get {
                return ResourceManager.GetString("DebugHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the RNG with a new seed.
        /// </summary>
        internal static string DebugNewSeed {
            get {
                return ResourceManager.GetString("DebugNewSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God has taken an interest in your life. You lose 1 health..
        /// </summary>
        internal static string DebugSmite {
            get {
                return ResourceManager.GetString("DebugSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn a Wolf Nearby.
        /// </summary>
        internal static string DebugSpawnNear {
            get {
                return ResourceManager.GetString("DebugSpawnNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn a Wolf at a Random Location.
        /// </summary>
        internal static string DebugSpawnRandom {
            get {
                return ResourceManager.GetString("DebugSpawnRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} succumbs to its wounds..
        /// </summary>
        internal static string EnemyDeath {
            get {
                return ResourceManager.GetString("EnemyDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You feel rejuvenated. Your health is restored to full..
        /// </summary>
        internal static string FullHeal {
            get {
                return ResourceManager.GetString("FullHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gain {0} experience..
        /// </summary>
        internal static string GainExperience {
            get {
                return ResourceManager.GetString("GainExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satan&apos;s Lil Helper.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You consume the potion, restoring {0} health..
        /// </summary>
        internal static string HealPotionMessage {
            get {
                return ResourceManager.GetString("HealPotionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish your turn.
        /// </summary>
        internal static string HelpF {
            get {
                return ResourceManager.GetString("HelpF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the help screen (you&apos;re already here!).
        /// </summary>
        internal static string HelpH {
            get {
                return ResourceManager.GetString("HelpH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your Inventory.
        /// </summary>
        internal static string HelpI {
            get {
                return ResourceManager.GetString("HelpI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        internal static string HelpMovement {
            get {
                return ResourceManager.GetString("HelpMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or (numpad).
        /// </summary>
        internal static string HelpOr {
            get {
                return ResourceManager.GetString("HelpOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your Skills and Spells.
        /// </summary>
        internal static string HelpS {
            get {
                return ResourceManager.GetString("HelpS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory_Title {
            get {
                return ResourceManager.GetString("Inventory.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing but the void in that direction..
        /// </summary>
        internal static string MapEdge {
            get {
                return ResourceManager.GetString("MapEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That way is blocked..
        /// </summary>
        internal static string PathBlocked {
            get {
                return ResourceManager.GetString("PathBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attack {0}, dealing {1} damage..
        /// </summary>
        internal static string PlayerAttack {
            get {
                return ResourceManager.GetString("PlayerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You land a powerful strike!.
        /// </summary>
        internal static string PowerfulStrike {
            get {
                return ResourceManager.GetString("PowerfulStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show enemy health bars: {0}.
        /// </summary>
        internal static string SettingsShowHealthBars {
            get {
                return ResourceManager.GetString("SettingsShowHealthBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Grimoire is not yet implemented!.
        /// </summary>
        internal static string SpellBook {
            get {
                return ResourceManager.GetString("SpellBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacks: {0}/{1}.
        /// </summary>
        internal static string StatusAttacks {
            get {
                return ResourceManager.GetString("StatusAttacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health: {0:D} / {1:D}.
        /// </summary>
        internal static string StatusHealth {
            get {
                return ResourceManager.GetString("StatusHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0:D2}, {1:D2}.
        /// </summary>
        internal static string StatusLocation {
            get {
                return ResourceManager.GetString("StatusLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana: {0:D} / {1:D}.
        /// </summary>
        internal static string StatusMana {
            get {
                return ResourceManager.GetString("StatusMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves: {0}/{1}.
        /// </summary>
        internal static string StatusMoves {
            get {
                return ResourceManager.GetString("StatusMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done this turn:.
        /// </summary>
        internal static string StatusTurn {
            get {
                return ResourceManager.GetString("StatusTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a mysterious stranger.
        /// </summary>
        internal static string Stranger {
            get {
                return ResourceManager.GetString("Stranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit to Desktop.
        /// </summary>
        internal static string ToDesktop {
            get {
                return ResourceManager.GetString("ToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit to Menu.
        /// </summary>
        internal static string ToMenu {
            get {
                return ResourceManager.GetString("ToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Your Bestiary.
        /// </summary>
        internal static string ViewBestiary {
            get {
                return ResourceManager.GetString("ViewBestiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ViewSettings {
            get {
                return ResourceManager.GetString("ViewSettings", resourceCulture);
            }
        }
    }
}
